// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  hero: dynamic(() => import("./Hero")),
  opening: dynamic(() => import("./Opening")),
  prices: dynamic(() => import("./Prices")),
  services: dynamic(() => import("./Services")),
};
